// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeirrPOg13HGoC8o0LUYfxVOiOccGNc-U',
    appId: '1:886236334997:web:7bbb493e5f5280dea4849c',
    messagingSenderId: '886236334997',
    projectId: 'chat-app-25a75',
    authDomain: 'chat-app-25a75.firebaseapp.com',
    storageBucket: 'chat-app-25a75.appspot.com',
    measurementId: 'G-C4B514D39L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEFOltnQ-8uB8z6IazTiozrdkSZ8-Ntc',
    appId: '1:886236334997:android:7c05c53da901218ca4849c',
    messagingSenderId: '886236334997',
    projectId: 'chat-app-25a75',
    storageBucket: 'chat-app-25a75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjkxsyGy1dqeZybyHkwlWsXuqCUv652E',
    appId: '1:886236334997:ios:20027677b697d369a4849c',
    messagingSenderId: '886236334997',
    projectId: 'chat-app-25a75',
    storageBucket: 'chat-app-25a75.appspot.com',
    iosClientId: '886236334997-31v3diu7e4bp73pkpn3hhvmk8qn1kl4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
